language: node_js
sudo: false
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
env:
  global:
  - secure: gZ5vpMlc9fuKSZeMmT6xf4+FIVWxET6f6Lkp6l5Qo9vL2X/KC/bMJF1v2w5xXFLFTdm/hPUDkeQRDUBBJhGcsXhJeWIvAXdPkObV9ZPRwpDnnN1qU5lOqVIy6gFjDm2Wm6UNXcRnyP1TrGpMwbG13EUtD0rF8LZqBm3B833sKS4=
  - secure: DObDewETPYiIsASeC3UETPbQ6YBniRZdNV2eTM1xULvuFNDxXJD09KKyWOiMduublEIJRXLjBIXmD8cbVsgrbRUYA4bxcXffDeuc6q6HaQGU9HvIbLz6o3/oxi4fX2G9GwrZtijW2p2Rgw2l9koR3ovjcM97CSTWFUMh5rtXag8=
  - CXX=g++-4.8
  - secure: EhHV7Uf6V+RenASUttifZ5/N09em1dgFv2XCDnyD7dG7nYXQ2skP5hqZ8Yl+7bZ9UbgPTE7EeJdDBwuCJPK3Rbeycj9E6fBdx/lxfQDw76tuO7Cp8jC7h8Q0RIsj5yz1dz3XoMhAjNFfgjugg3iYyBBxOcAUkqWIHdfCzjikXLPyPtcVkByZ5gpj71mqG2UBTwxolsDxWysailUw9VCLzj14DBMOaKjoiNUqWssP0lNi6RP4Gifj4IpPLpJmE+NRhRv+w/JgEp0UQBwxZu8JL81HsMBT4650FkMDqrGvbuSrL4XXqxBuh1FQ/daEjbG+b/fAJUnoc63WEuDCTn7nXqgngEFO2DARYTsl2uO/ZzRb4L0SEKQt5Pp6A/A7UOxUFlyD1vQGv1g5i5FW4GKpv3UT9AsFQkFWoG4tKLDrXqMIkePEXz3qOnK/I5z6kekTLs+3O0ZjhnGtSRE87rQ/OPy5bzSQexCNFDDhHe3BaRAfJe3ibjX3lKQ4Fs+H/6Y6uO8JtfEtu/jfVNSHo75kPwlK3oRVMlZTiwMPNJpuZ1+mAJc2X9M4Jb5VrkRNOlT0VULuhd5rA4UwWgLhYcnX6EUwwtpElHVMolhSgCBrE8baswC9JbscLa9Y2APfcanZNPmn8X4vtKmLEsVX3lzv6m7X2jA1XKdd4CdVXylFst8=
  - secure: BphXFD8Ug8xsff9uDzL3u9CpkAXQSsJ10J8DrKQX7+Bf1z+szDxnL5UyFoL7nxTJ/dYViRIVG8DKXF3o/aWr4EbhDyW2ty/tWgzkaPEHLNcc2vLfeVYEweCZkrKN52B3pDHDNmphjTCK42BZJt2Xvuv3n+6wN99ZMhJuel0fIOfiprXSOExYbFZdaYJ5QfeEcIXDGpMgOyYmgZDAHS9Lj6VKu1734xsAlq+cYdalvQ3kRVuPBhNy8YCsjcfphGtw+CqBeq0RMCubn70z/nGGBgB5VVY0wDUj6lgvIVzMyKhRhuu7mVSvQrguvqEGiIfFnq5pAZgTcPY0Ax1jZkwSj66AcLbg5KbbM6kdCUhghW3gQV/YxAltxiZ3vDfaYc7jznfu73xMuqsSs3PFkfuMXs3Vk5nWD+mjprH1XDUBbrSD4pLST1CvxMrfH55cxoaZk0Cs/YigyDAdYKaj5PdOYHCBf2W9Vk3CNFiCpciGcBWQEhnVz4GORQiqO6XLv+/xbyCK92GoYXuJNe7IYs4Jb5DL6e32I+TKEKQz1YPx7li5Iiy+6vxdKXKeLCj1piVbRsPGVU+8uonahFGvuSU5GqplcT0ick6wN7RaAwUP0GZWH6qCTcZ2lQyF9PvUYcrqylsZg9XhMNkdxBBnG8ZSs4RSYpooPj1D46vn86nkH+k=
  - secure: IjxVfXigbQsBjRdKb9II4eyYqsRBPIxpDdtPizasykp+Hu60R+gblxmZ7DoIjJN33tADh30eo0LcgAQxuxIHweXCV96ZGwDKk3WpNInNIKIilmpe58t4u985yYTevwjzEXRlW9l4MsZ4ARmV3Fpjn4ogVGbRH4LJ208nlqj8Il1B/5E0A7Z4AkRjWbip12OYe41GdM39LenYheNnN8txxSOJTMIiQDWumbwxC6G7/c2Iw7Qa8HcXLqGS1B4fc+gymOWUUFtwf+/mUj4Z6RyI12bbrTg6ZAK9cVp8eTDxmCtKUKhVKTwACxu0q59K+/ZWIWDyJ2pFrk0U48vLemhecsvBBfmSgohDNXCArYAU1APXpGz0xd8f22jRshXNqNJv0JkLwOn3nIFajyAJx6XcrhafRIaobhJQmRtwNmlDK5MrJB4+GINjTe1SxdNZgu7TXWZ7daqlQ53+CbZyRv82auRT6Tb6gSkHRaxrzCn5OUuEPK4p4S1IKHdP3Lg94fwDwPZug4Q3JYA8e4F3qOzrGjbC629OH8LMYfT3liDFinEObYvjHmWoRlWzkj+J8JOzKjCArAOSY9BY+/JbxO6FDfhuyOLwezoymvuaPOTjW/PpntOkd5+4XrThV0KE6UrnisBNNA5xCeXOgcjjAda3B316nMrVcakvqvK1ZukDVnE=
  - secure: LdrIHTOXJrgv4sZSV6pGq4pNU4aKErvc2xmXeN4u91Fp+Q2LnfStv5Wb8m5Jw09HQbdBRv8XXtKtxEpqPwVTKJCUXx/pkjxIy5PQrzEM5xSICAKbXM4Kg/ImAgvX1aZP5XI/lkh6k+z86IJQBR0cDRWBNRRXK0v/LUpmH6kTNahjDfQCfj9XF7ud3WEDM0TOnnP7ez0F3IUjMSLUrA6Vb/pRq39vrMP/lIGk6whmV4cDL1oELVGJXfwkRM9PsnImr7+UK2TVvLp3hScT/aWZlmUQ7jQGgyEbZOprsdFgOwwNCfna9QPCxpDBPJtBTI56J7sCiXGXd2RNpyHID2xRB/KimcvagsBwOE8t2SF+W/W8Gx+eBU4VMQoI/fKTC/li8nHHev5m0BGd4NShQX2wcPrPKd8/09yPWxieyYLN519SJiYuY2Y7zD3PX/ps2i2VM1u3V5dyzCK2+mNsqdvCWFu6i+gwj+cpyafvHGibdsbqQKy1HQhv9v1QuzpSdhBiqgiqvZahO6jTxCAxX+xdwQz16gWent/t75mq31VBNRxDyjZJTurnRa16mqc/KerwrheSumPwkJ8LERA9onLWeFhFEd6mgnaWeWfCOgTAPcGIogQ37jjWg7TRHUs6H3w3FmgCnX9LCuFsDMaED/1EaOZp7LPq3dh6m3alSP6csFQ=
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    - ubuntu-toolchain-r-test
    packages:
    - google-chrome-stable
    - g++-4.8
  sauce_connect: true
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local -s 'default';
  fi
